name: AirbnbClone
options:
  bundleIdPrefix: com.scaleify
  createIntermediateGroups: true
  defaultConfig: Debug
  deploymentTarget:
    iOS: 16.0

settings:
  SWIFT_VERSION: 5.0
  TARGETED_DEVICE_FAMILY: "1,2"
  IPHONEOS_DEPLOYMENT_TARGET: 16.0

targets:
  AirbnbClone:
    type: application
    platform: iOS
    sources:
      - path: AirbnbClone
        excludes:
          - "**/*.xcassets"
          - "**/*.plist"
    resources:
      - AirbnbClone/Assets.xcassets
      - path: AirbnbClone/Preview Content
        type: folder
    info:
      path: AirbnbClone/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.scaleify.airbnbclone
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ENABLE_PREVIEWS: true
      DEVELOPMENT_ASSET_PATHS: "AirbnbClone/Preview Content"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""

schemes:
  AirbnbClone:
    build:
      targets:
        AirbnbClone: all
    run:
      config: Debug
      debugEnabled: true
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release